version: '3'
services:
    web-service:
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
        container_name: web-service
        ports:
            - "8080:8080"
            - "8000:8000"
        environment:
            # Adapter
            - security.type=embedded
